name: pyfinance-env

dependencies:
  - ipykernel=5.3
  - ipython=7.13
  - matplotlib=3.1
  - pandas=1.0
  - pip=20.0
  - python=3.8
  - scikit-learn=0.22
  - statsmodels=0.12.2
  - pip:
    - yfinance==0.1.62
    - jupyter
    - PyPortfolioOpt==1.4.2
    - plotly==5.2.1

